# **Automatidata project**
**Course 5 - The Nuts and bolts of machine learning**

You are a data professional in a data analytics firm called Automatidata. Their client, the New York City Taxi & Limousine Commission (New York City TLC), was impressed with the work you have done and has requested that you **build a machine learning model to predict if a customer will not leave a tip**. They want to use the model in an app that will alert taxi drivers to customers who are unlikely to tip, since drivers depend on tips.

A notebook was structured and prepared to help you in this project. Please complete the following questions.

# Course 5 End-of-course project: Build a machine learning model

In this activity, you will practice using tree-based modeling techniques to predict on a binary target class.  
<br/>   

**The purpose** of this model is to find ways to generate more revenue for taxi cab drivers.  
  
**The goal** of this model is to predict whether or not a customer is a generous tipper.  
<br/>  

*This activity has three parts:*

**Part 1:** Ethical considerations 
* Consider the ethical implications of the request 

* Should the objective of the model be adjusted?

**Part 2:** Feature engineering

* Perform feature selection, extraction, and transformation to prepare the data for modeling

**Part 3:** Modeling

* Build the models, evaluate them, and advise on next steps

Follow the instructions and answer the questions below to complete the activity. Then, complete an Executive Summary using the questions listed on the PACE Strategy Document. 

Be sure to complete this activity before moving on. The next course item will provide you with a completed exemplar to compare to your own work.

# Build a machine learning model

<img src="images/Pace.png" width="100" height="100" align=left>

# **PACE stages**

Throughout these project notebooks, you'll see references to the problem-solving framework PACE. The following notebook components are labeled with the respective PACE stage: Plan, Analyze, Construct, and Execute.

<img src="images/Plan.png" width="100" height="100" align=left>


## PACE: Plan 

Consider the questions in your PACE Strategy Document to reflect on the Plan stage.

In this stage, consider the following questions:

1.   What are you being asked to do?


2.   What are the ethical implications of the model? What are the consequences of your model making errors?
  *   What is the likely effect of the model when it predicts a false negative (i.e., when the model says a customer will give a tip, but they actually won't)?
  
  *   What is the likely effect of the model when it predicts a false positive (i.e., when the model says a customer will not give a tip, but they actually will)?  
  
  
3.   Do the benefits of such a model outweigh the potential problems?
  
4.   Would you proceed with the request to build this model? Why or why not?
 
5.   Can the objective be modified to make it less problematic?

### 1. What are you being asked to do?
You are being asked to build a machine learning model that predicts whether a taxi customer will leave a tip or not. The intended use is to alert drivers about customers who are unlikely to tip, so they can adjust expectations or behavior.

---

### 2. What are the ethical implications of the model? What are the consequences of your model making errors?
- **Ethical implications:**  
  - Risk of discrimination: Drivers may treat passengers unfairly based on predictions.  
  - Privacy concerns: Using customer data for behavioral predictions can be intrusive.  
  - Bias amplification: If historical tipping patterns reflect socioeconomic or demographic biases, the model could perpetuate them.  
- **Consequences of errors:**  
  - False negatives and false positives could lead to unfair treatment of customers, loss of trust, and reputational damage for NYC TLC.

---

### 3. What is the likely effect of the model when it predicts a false negative (model says customer will tip, but they don’t)?
- Drivers may expect a tip and provide good service, but end up disappointed.  
- Could reduce driver morale and trust in the system.  
- Financial impact: drivers may lose potential revenue they anticipated.

---

### 4. What is the likely effect of the model when it predicts a false positive (model says customer won’t tip, but they actually do)?
- Drivers may provide lower-quality service, assuming no tip, which could frustrate customers.  
- Customers who intended to tip may feel mistreated and decide not to tip after all.  
- This could harm customer satisfaction and loyalty.

---

### 5. Do the benefits of such a model outweigh the potential problems? Would you proceed with the request to build this model? Can the objective be modified to make it less problematic?
- **Benefits vs problems:** The risks of unfair treatment and bias outweigh the benefits of predicting individual tipping behavior.  
- **Proceed or not:** I would **not proceed** with the model in its current form, because it could harm customer relationships and driver reputation.  
- **Modified objective:** Instead of predicting individual tipping, the model could be reframed to:  
  - Identify **aggregate patterns** of tipping behavior (e.g., time of day, trip length, payment method).  
  - Provide **insights for driver training or policy changes** (e.g., fare adjustments, incentive programs).  
  - Predict **tip likelihood ranges** rather than binary “no tip” vs “tip,” reducing stigma and bias.

---

✅ This way, the project remains useful for drivers and NYC TLC while avoiding ethical pitfalls.

Suppose you were to modify the modeling objective so, instead of predicting people who won't tip at all, you predicted people who are particularly generous&mdash;those who will tip 20% or more? Consider the following questions:

1.  What features do you need to make this prediction?

2.  What would be the target variable?  

3.  What metric should you use to evaluate your model? Do you have enough information to decide this now?

### 1. What features do you need to make this prediction?
- **Trip characteristics:** distance, duration, fare amount (excluding tip).  
- **Temporal features:** time of day, day of week, weekday vs weekend, rush hour flag.  
- **Passenger details:** passenger count.  
- **Payment method:** cash vs card.  
- **Derived features:** fare per mile/minute, tip percentage (for training), categorical encodings for time buckets.  

---

### 2. What would be the target variable?
- A **binary variable** indicating whether the tip percentage is **≥20% (generous tipper)** or **<20% (not generous tipper)**.  
- This reframing avoids labeling customers negatively and instead highlights positive behavior.

---

### 3. What metric should you use to evaluate your model? Do you have enough information to decide this now?
- **Primary metrics:**  
  - **Precision and Recall** for the “generous tipper” class (important to minimize false positives and false negatives).  
  - **F1‑score** to balance precision and recall.  
  - **ROC‑AUC** to evaluate overall classification performance.  
- **Do we have enough information now?**  
  - Not fully. We need to check class balance (how many rides actually have ≥20% tips). If the class is imbalanced, metrics like accuracy will be misleading, and we’ll rely more on precision/recall and AUC.  

---

✅ This way, the model focuses on identifying **positive tipping behavior** and uses evaluation metrics that reflect the importance of correctly identifying generous tippers.


**_Complete the following steps to begin:_**

### **Task 1. Imports and data loading**

Import packages and libraries needed to build and evaluate random forest and XGBoost classification models.

In [4]:
#==> ENTER YOUR CODE HERE

# Core packages
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn models and utilities
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    accuracy_score, 
    precision_score, 
    recall_score, 
    f1_score, 
    roc_auc_score, 
    confusion_matrix, 
    classification_report
)
from sklearn.ensemble import RandomForestClassifier

# XGBoost
from xgboost import XGBClassifier

# Optional: warnings filter for cleaner output
import warnings
warnings.filterwarnings("ignore")

In [7]:
import pandas as pd

# Load the dataset using the correct filename
df = pd.read_csv("2017_Yellow_Taxi_Trip_Data.csv")

# Quick check of shape and first few rows
print("Dataset shape:", df.shape)
df.head()

Dataset shape: (22699, 18)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

Begin by reading in the data. There are two dataframes: one containing the original data, the other containing the mean durations, mean distances, and predicted fares from the previous course's project called nyc_preds_means.csv.

**Note:** `Pandas` reads in the dataset as `df0`, now inspect the first five rows. As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [8]:
# Load dataset into dataframe
df0 = pd.read_csv('2017_Yellow_Taxi_Trip_Data.csv')

# Import predicted fares and mean distance and duration from previous course
nyc_preds_means = pd.read_csv('nyc_preds_means.csv')

# Inspect the first five rows of each
print("Original taxi trip data:")
display(df0.head())

print("Predicted fares and means data:")
display(nyc_preds_means.head())

Original taxi trip data:

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

Predicted fares and means data:

   mean_duration  mean_distance  predicted_fare
0      22.847222       3.521667       16.434245
1      24.470370       3.108889       16.052218
2       7.250000       0.881429        7.053706
3      30.250000       3.700000       18.731650
4      14.616667       4.435000       15.845642

Inspect the first few rows of `df0`.

In [9]:
# Inspect the first few rows of df0
df0.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

Inspect the first few rows of `nyc_preds_means`.

In [10]:
# Inspect the first few rows of nyc_preds_means
nyc_preds_means.head()

   mean_duration  mean_distance  predicted_fare
0      22.847222       3.521667       16.434245
1      24.470370       3.108889       16.052218
2       7.250000       0.881429        7.053706
3      30.250000       3.700000       18.731650
4      14.616667       4.435000       15.845642

#### Join the two dataframes

Join the two dataframes using a method of your choice.

In [14]:
# Concatenate the two dataframes side by side (same row order)
df = pd.concat([df0, nyc_preds_means], axis=1)

# Inspect the merged dataframe
print("Merged dataset shape:", df.shape)
df.head()

Merged dataset shape: (22699, 21)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,...,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,mean_duration,mean_distance,predicted_fare
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,...,13.0,0.0,0.5,2.76,0.0,0.3,16.56,22.847222,3.521667,16.434245
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,...,16.0,0.0,0.5,4.00,0.0,0.3,20.80,24.470370,3.108889,16.052218
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,...,6.5,0.0,0.5,1.45,0.0,0.3,8.75,7.250000,0.881429,7.053706
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,...,20.5,0.0,0.5,6.39,0.0,0.3,27.69,30.250000,3.700000,18.731650
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,...,16.5,0.5,0.5,0.00,0.0,0.3,17.80,14.616667,4.435000,15.845642

<img src="images/Analyze.png" width="100" height="100" align=left>

## PACE: **Analyze**

Consider the questions in your PACE Strategy Documentto reflect on the Analyze stage.

### **Task 2. Feature engineering**

You have already prepared much of this data and performed exploratory data analysis (EDA) in previous courses. 

Call `info()` on the new combined dataframe.

In [15]:
# Inspect the combined dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22699 entries, 0 to 22698
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             22699 non-null  int64
 1   VendorID               22699 non-null  int64
 2   tpep_pickup_datetime   22699 non-null  object
 3   tpep_dropoff_datetime  22699 non-null  object
 4   passenger_count        22699 non-null  int64
 5   trip_distance          22699 non-null  float64
 6   RatecodeID             22699 non-null  int64
 7   store_and_fwd_flag     22699 non-null  object
 8   PULocationID           22699 non-null  int64
 9   DOLocationID           22699 non-null  int64
 10  payment_type           22699 non-null  int64
 11  fare_amount            22699 non-null  float64
 12  extra                  22699 non-null  float64
 13  mta_tax                22699 non-null  float64
 14  tip_amount             22699 non-null  float64
 15  tolls_amount           22699 non-null  float64
 16  improvement_surcharge  22699 non-null  float64
 17  total_amount           22699 non-null  float64
 18  mean_duration          22699 non-null  float64
 19  mean_distance          22699 non-null  float64
 20  predicted_fare         22699 non-null  float64
dtypes: float64(11), int64(7), object(3)
memory usage: 3.6+ MB

You know from your EDA that customers who pay cash generally have a tip amount of $0. To meet the modeling objective, you'll need to sample the data to select only the customers who pay with credit card. 

Copy `df0` and assign the result to a variable called `df1`. Then, use a Boolean mask to filter `df1` so it contains only customers who paid with credit card.

In [16]:
# Copy the original dataframe
df1 = df0.copy()

# Filter for customers who paid with credit card (payment_type == 1)
df1 = df1[df1['payment_type'] == 1]

# Inspect the first few rows
df1.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
5,23345809,2,03/25/2017 8:34:11 PM,03/25/2017 8:42:11 PM,6,2.30,1,N,161,236,1,9.0,0.5,0.5,2.06,0.0,0.3,12.36

##### **Target**

Notice that there isn't a column that indicates tip percent, which is what you need to create the target variable. You'll have to engineer it. 

Add a `tip_percent` column to the dataframe by performing the following calculation:  
<br/>  


$$tip\ percent = \frac{tip\ amount}{total\ amount - tip\ amount}$$  

Round the result to three places beyond the decimal. **This is an important step.** It affects how many customers are labeled as generous tippers. In fact, without performing this step, approximately 1,800 people who do tip ≥ 20% would be labeled as not generous. 

To understand why, you must consider how floats work. Computers make their calculations using floating-point arithmetic (hence the word "float"). Floating-point arithmetic is a system that allows computers to express both very large numbers and very small numbers with a high degree of precision, encoded in binary. However, precision is limited by the number of bits used to represent a number, which is generally 32 or 64, depending on the capabilities of your operating system. 

This comes with limitations in that sometimes calculations that should result in clean, precise values end up being encoded as very long decimals. Take, for example, the following calculation:

In [17]:
# Add tip_percent column
df1['tip_percent'] = df1['tip_amount'] / (df1['total_amount'] - df1['tip_amount'])

# Round to 3 decimal places
df1['tip_percent'] = df1['tip_percent'].round(3)

# Inspect the first few rows
df1[['fare_amount', 'tip_amount', 'total_amount', 'tip_percent']].head()

   fare_amount  tip_amount  total_amount  tip_percent
0         13.0        2.76         16.56        0.200
1         16.0        4.00         20.80        0.238
2          6.5        1.45          8.75        0.199
3         20.5        6.39         27.69        0.300
5          9.0        2.06         12.36        0.200

Notice the three that is 16 places to the right of the decimal. As a consequence, if you were to then have a step in your code that identifies values ≤ 3.3, this would not be included in the result. Therefore, whenever you perform a calculation to compute a number that is then used to make an important decision or filtration, round the number. How many degrees of precision you round to is your decision, which should be based on your use case. 

Refer to this [guide for more information related to floating-point arithmetic](https://floating-point-gui.de/formats/fp/).

In [18]:
# Create tip_percent column
df1['tip_percent'] = df1['tip_amount'] / (df1['total_amount'] - df1['tip_amount'])

# Round to 3 decimal places to avoid floating-point precision issues
df1['tip_percent'] = df1['tip_percent'].round(3)

# Inspect the first few rows to confirm
df1[['fare_amount', 'tip_amount', 'total_amount', 'tip_percent']].head()

   fare_amount  tip_amount  total_amount  tip_percent
0         13.0        2.76         16.56        0.200
1         16.0        4.00         20.80        0.238
2          6.5        1.45          8.75        0.199
3         20.5        6.39         27.69        0.300
5          9.0        2.06         12.36        0.200

Now create another column called `generous`. This will be the target variable. The column should be a binary indicator of whether or not a customer tipped ≥ 20% (0=no, 1=yes).

1. Begin by making the `generous` column a copy of the `tip_percent` column.
2. Reassign the column by converting it to Boolean (True/False).
3. Reassign the column by converting Boolean to binary (1/0).

In [19]:
# Create 'generous' column (target)

# 1. Copy tip_percent column
df1['generous'] = df1['tip_percent']

# 2. Convert to Boolean (True if tip_percent >= 0.20, else False)
df1['generous'] = df1['generous'] >= 0.20

# 3. Convert Boolean to binary (1 for True, 0 for False)
df1['generous'] = df1['generous'].astype(int)

# Inspect the first few rows
df1[['tip_percent', 'generous']].head()

   tip_percent  generous
0        0.200         1
1        0.238         1
2        0.199         0
3        0.300         1
5        0.200         1

<details>
  <summary><h5>HINT</h5></summary>

To convert from Boolean to binary, use `.astype(int)` on the column.
</details>

#### Create day column

Next, you're going to be working with the pickup and dropoff columns.

Convert the `tpep_pickup_datetime` and `tpep_dropoff_datetime` columns to datetime.

In [20]:
# Convert pickup and dropoff cols to datetime
df1['tpep_pickup_datetime'] = pd.to_datetime(df1['tpep_pickup_datetime'])
df1['tpep_dropoff_datetime'] = pd.to_datetime(df1['tpep_dropoff_datetime'])

# Inspect the first few rows to confirm conversion
df1[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].head()

  tpep_pickup_datetime tpep_dropoff_datetime
0  2017-03-25 08:55:43   2017-03-25 09:09:47
1  2017-04-11 14:53:28   2017-04-11 15:19:58
2  2017-12-15 07:26:56   2017-12-15 07:34:08
3  2017-05-07 13:17:59   2017-05-07 13:48:14
5  2017-03-25 20:34:11   2017-03-25 20:42:11

Create a `day` column that contains only the day of the week when each passenger was picked up. Then, convert the values to lowercase.

In [21]:
# Create a 'day' column from pickup datetime
df1['day'] = df1['tpep_pickup_datetime'].dt.day_name().str.lower()

# Inspect the first few rows
df1[['tpep_pickup_datetime', 'day']].head()

  tpep_pickup_datetime       day
0  2017-03-25 08:55:43  saturday
1  2017-04-11 14:53:28   tuesday
2  2017-12-15 07:26:56    friday
3  2017-05-07 13:17:59    sunday
5  2017-03-25 20:34:11  saturday


<details>
  <summary><h5>HINT</h5></summary>

To convert to day name, use `dt.day_name()` on the column.
</details>

#### Create time of day columns

Next, engineer four new columns that represent time of day bins. Each column should contain binary values (0=no, 1=yes) that indicate whether a trip began (picked up) during the following times:

`am_rush` = [06:00&ndash;10:00)  
`daytime` = [10:00&ndash;16:00)  
`pm_rush` = [16:00&ndash;20:00)  
`nighttime` = [20:00&ndash;06:00)  

To do this, first create the four columns. For now, each new column should be identical and contain the same information: the hour (only) from the `tpep_pickup_datetime` column.

In [22]:
# Extract pickup hour
pickup_hour = df1['tpep_pickup_datetime'].dt.hour

# Create 'am_rush' col
df1['am_rush'] = pickup_hour

# Create 'daytime' col
df1['daytime'] = pickup_hour

# Create 'pm_rush' col
df1['pm_rush'] = pickup_hour

# Create 'nighttime' col
df1['nighttime'] = pickup_hour

# Inspect the first few rows
df1[['tpep_pickup_datetime', 'am_rush', 'daytime', 'pm_rush', 'nighttime']].head()

  tpep_pickup_datetime  am_rush  daytime  pm_rush  nighttime
0  2017-03-25 08:55:43        8        8        8          8
1  2017-04-11 14:53:28       14       14       14         14
2  2017-12-15 07:26:56        7        7        7          7
3  2017-05-07 13:17:59       13       13       13         13
5  2017-03-25 20:34:11       20       20       20         20

You'll need to write four functions to convert each new column to binary (0/1). Begin with `am_rush`. Complete the function so if the hour is between [06:00–10:00), it returns 1, otherwise, it returns 0.

In [23]:
# Define 'am_rush()' conversion function [06:00–10:00)
def am_rush(hour):
    """
    Returns 1 if hour is between 6 and 9 (06:00–09:59), else 0.
    """
    if 6 <= hour < 10:
        return 1
    else:
        return 0

# Apply the function to the 'am_rush' column
df1['am_rush'] = df1['am_rush'].apply(am_rush)

# Quick check
df1[['tpep_pickup_datetime', 'am_rush']].head(10)

   tpep_pickup_datetime  am_rush
0   2017-03-25 08:55:43        1
1   2017-04-11 14:53:28        0
2   2017-12-15 07:26:56        1
3   2017-05-07 13:17:59        0
5   2017-03-25 20:34:11        0
6   2017-05-03 19:04:09        0
7   2017-08-15 17:41:06        0
9   2017-11-10 15:20:29        0
10  2017-03-04 11:58:00        0
11  2017-03-05 19:15:30        0

Now, apply the `am_rush()` function to the `am_rush` series to perform the conversion. Print the first five values of the column to make sure it did what you expected it to do.

**Note:** Be careful! If you run this cell twice, the function will be reapplied and the values will all be changed to 0.

In [24]:
# Apply 'am_rush' function to the 'am_rush' series
df1['am_rush'] = df1['am_rush'].apply(am_rush)

# Print the first five values of the column
print(df1['am_rush'].head())

0    0
1    0
2    0
3    0
5    0
Name: am_rush, dtype: int64

Write functions to convert the three remaining columns and apply them to their respective series.

In [25]:
# Define 'daytime()' conversion function [10:00–16:00)
def daytime(hour):
    """
    Returns 1 if hour is between 10 and 15 (10:00–15:59), else 0.
    """
    if 10 <= hour < 16:
        return 1
    else:
        return 0

# Apply the function to the 'daytime' column
df1['daytime'] = df1['daytime'].apply(daytime)

# Quick check
print(df1['daytime'].head())

0    0
1    1
2    0
3    1
5    0
Name: daytime, dtype: int64

In [26]:
# Apply 'daytime()' function to the 'daytime' series
df1['daytime'] = df1['daytime'].apply(daytime)

# Print the first five values of the column
print(df1['daytime'].head())

0    0
1    0
2    0
3    0
5    0
Name: daytime, dtype: int64

In [27]:
# Define 'pm_rush()' conversion function [16:00–20:00)
def pm_rush(hour):
    """
    Returns 1 if hour is between 16 and 19 (16:00–19:59), else 0.
    """
    if 16 <= hour < 20:
        return 1
    else:
        return 0

# Apply the function to the 'pm_rush' column
df1['pm_rush'] = df1['pm_rush'].apply(pm_rush)

# Quick check
print(df1['pm_rush'].head())

0    0
1    0
2    0
3    0
5    0
Name: pm_rush, dtype: int64

In [28]:
# Apply 'pm_rush()' function to the 'pm_rush' series
df1['pm_rush'] = df1['pm_rush'].apply(pm_rush)

# Print the first five values of the column
print(df1['pm_rush'].head())

0    0
1    0
2    0
3    0
5    0
Name: pm_rush, dtype: int64

In [29]:
# Define 'nighttime()' conversion function [20:00–06:00)
def nighttime(hour):
    """
    Returns 1 if hour is between 20:00–23:59 or 00:00–05:59, else 0.
    """
    if (20 <= hour <= 23) or (0 <= hour < 6):
        return 1
    else:
        return 0

# Apply the function to the 'nighttime' column
df1['nighttime'] = df1['nighttime'].apply(nighttime)

# Quick check
print(df1['nighttime'].head())

0    0
1    0
2    0
3    0
5    1
Name: nighttime, dtype: int64

In [30]:
# Apply 'nighttime()' function to the 'nighttime' series
df1['nighttime'] = df1['nighttime'].apply(nighttime)

# Print the first five values of the column
print(df1['nighttime'].head())

0    1
1    1
2    1
3    1
5    1
Name: nighttime, dtype: int64

#### Create `month` column

Now, create a `month` column that contains only the abbreviated name of the month when each passenger was picked up, then convert the result to lowercase.

<details>
  <summary><h5>HINT</h5></summary>

Refer to the [strftime cheatsheet](https://strftime.org/) for help.
</details>

In [31]:
# Create 'month' col
df1['month'] = df1['tpep_pickup_datetime'].dt.strftime('%b').str.lower()

# Inspect the first few rows
df1[['tpep_pickup_datetime', 'month']].head()

  tpep_pickup_datetime month
0  2017-03-25 08:55:43   mar
1  2017-04-11 14:53:28   apr
2  2017-12-15 07:26:56   dec
3  2017-05-07 13:17:59   may
5  2017-03-25 20:34:11   mar

Examine the first five rows of your dataframe.

In [32]:
# Examine the first five rows of the dataframe
print(df1.head())

   Unnamed: 0  VendorID tpep_pickup_datetime tpep_dropoff_datetime  \
0    24870114         2  2017-03-25 08:55:43   2017-03-25 09:09:47
1    35634249         1  2017-04-11 14:53:28   2017-04-11 15:19:58
2   106203690         1  2017-12-15 07:26:56   2017-12-15 07:34:08
3    38942136         2  2017-05-07 13:17:59   2017-05-07 13:48:14
5    23345809         2  2017-03-25 20:34:11   2017-03-25 20:42:11

   passenger_count  trip_distance  RatecodeID store_and_fwd_flag  \
0                6           3.34           1                  N
1                1           1.80           1                  N
2                1           1.00           1                  N
3                1           3.70           1                  N
5                6           2.30           1                  N

   PULocationID  DOLocationID  ...  improvement_surcharge  total_amount  \
0           100           231  ...                    0.3         16.56
1           186            43  ...                    0.3         20.80
2           262           236  ...                    0.3          8.75
3           188            97  ...                    0.3         27.69
5           161           236  ...                    0.3         12.36

   tip_percent  generous       day  am_rush  daytime  pm_rush  nighttime  \
0        0.200         1  saturday        0        0        0          1
1        0.238         1   tuesday        0        0        0          1
2        0.199         0    friday        0        0        0          1
3        0.300         1    sunday        0        0        0          1
5        0.200         1  saturday        0        0        0          1

   month
0    mar
1    apr
2    dec
3    may
5    mar

[5 rows x 26 columns]

#### Drop columns

Drop redundant and irrelevant columns as well as those that would not be available when the model is deployed. This includes information like payment type, trip distance, tip amount, tip percentage, total amount, toll amount, etc. The target variable (`generous`) must remain in the data because it will get isolated as the `y` data for modeling.

In [34]:
# Drop redundant/irrelevant/unavailable columns safely
df_model = df1.drop(columns=[
    'payment_type',
    'trip_distance',
    'tip_amount',
    'tip_percent',
    'total_amount',
    'extra',
    'mta_tax',
    'improvement_surcharge',
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime'
], errors='ignore')

# Quick check of remaining columns
print(df_model.columns)

Index(['Unnamed: 0', 'VendorID', 'passenger_count', 'RatecodeID',
       'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'fare_amount',
       'tolls_amount', 'generous', 'day', 'am_rush', 'daytime', 'pm_rush',
       'nighttime', 'month'],
      dtype='object')

#### Variable encoding

Many of the columns are categorical and will need to be dummied (converted to binary). Some of these columns are numeric, but they actually encode categorical information, such as `RatecodeID` and the pickup and dropoff locations. To make these columns recognizable to the `get_dummies()` function as categorical variables, you'll first need to convert them to `type(str)`. 

1. Define a variable called `cols_to_str`, which is a list of the numeric columns that contain categorical information and must be converted to string: `RatecodeID`, `PULocationID`, `DOLocationID`.
2. Write a for loop that converts each column in `cols_to_str` to string.

In [35]:
# 1. Define list of cols to convert to string
cols_to_str = ['RatecodeID', 'PULocationID', 'DOLocationID']

# 2. Convert each column to string
for col in cols_to_str:
    df_model[col] = df_model[col].astype(str)

# Quick check
print(df_model[cols_to_str].dtypes)

RatecodeID      object
PULocationID    object
DOLocationID    object
dtype: object


<details>
  <summary><h5>HINT</h5></summary>

To convert to string, use `astype(str)` on the column.
</details>

Now convert all the categorical columns to binary.

1. Call `get_dummies()` on the dataframe and assign the results back to a new dataframe called `df2`.

In [36]:
# Convert categoricals to binary
df2 = pd.get_dummies(df_model, drop_first=True)

# Quick check of the new dataframe
print(df2.head())
print(df2.shape)

   Unnamed: 0  VendorID  passenger_count  fare_amount  tolls_amount  generous  \
0    24870114         2                6         13.0           0.0         1
1    35634249         1                1         16.0           0.0         1
2   106203690         1                1          6.5           0.0         0
3    38942136         2                1         20.5           0.0         1
5    23345809         2                6          9.0           0.0         1

   am_rush  daytime  pm_rush  nighttime  ...  month_dec  month_feb  month_jan  \
0        0        0        0          1  ...      False      False      False
1        0        0        0          1  ...      False      False      False
2        0        0        0          1  ...       True      False      False
3        0        0        0          1  ...      False      False      False
5        0        0        0          1  ...      False      False      False

   month_jul  month_jun  month_mar  month_may  month_nov  month_oct  month_sep
0      False      False       True      False      False      False      False
1      False      False      False      False      False      False      False
2      False      False      False      False      False      False      False
3      False      False      False       True      False      False      False
5      False      False       True      False      False      False      False

[5 rows x 348 columns]
(15265, 348)

##### Evaluation metric

Before modeling, you must decide on an evaluation metric. 

1. Examine the class balance of your target variable.

In [37]:
# Get class balance of 'generous' col
print(df2['generous'].value_counts())
print(df2['generous'].value_counts(normalize=True))

generous
1    8035
0    7230
Name: count, dtype: int64
generous
1    0.526368
0    0.473632
Name: proportion, dtype: float64

A little over half of the customers in this dataset were "generous" (tipped ≥ 20%). The dataset is very nearly balanced.

To determine a metric, consider the cost of both kinds of model error:
* False positives (the model predicts a tip ≥ 20%, but the customer does not give one)
* False negatives (the model predicts a tip < 20%, but the customer gives more)

False positives are worse for cab drivers, because they would pick up a customer expecting a good tip and then not receive one, frustrating the driver.

False negatives are worse for customers, because a cab driver would likely pick up a different customer who was predicted to tip more&mdash;even when the original customer would have tipped generously.

**The stakes are relatively even. You want to help taxi drivers make more money, but you don't want this to anger customers. Your metric should weigh both precision and recall equally. Which metric is this?**

The evaluation metric that weighs **precision and recall equally** is the **F1‑score**.  

✅ **Answer:** **F1‑score**  

---

### 🔹 Why F1‑score?
- **Precision** → protects drivers from false positives (predicting generous tip when it’s not).  
- **Recall** → protects customers from false negatives (missing generous tippers).  
- **F1‑score** → balances both, making it the fairest choice when the stakes are evenly matched and the dataset is nearly balanced.  

👉 With this decided, you can now move on to splitting your data into train/test sets and building your first model.

<img src="images/Construct.png" width="100" height="100" align=left>

## PACE: **Construct**

Consider the questions in your PACE Strategy Document to reflect on the Construct stage.

### **Task 3. Modeling**

##### **Split the data**

Now you're ready to model. The only remaining step is to split the data into features/target variable and training/testing data. 

1. Define a variable `y` that isolates the target variable (`generous`).
2. Define a variable `X` that isolates the features.
3. Split the data into training and testing sets. Put 20% of the samples into the test set, stratify the data, and set the random state.

In [38]:
# Isolate target variable (y)
y = df2['generous']

# Isolate the features (X)
X = df2.drop(columns=['generous'])

# Split into train and test sets (80/20 split, stratified, reproducible)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=0
)

# Quick check of shapes
print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training features shape: (12212, 347)
Testing features shape: (3053, 347)
Training target shape: (12212,)
Testing target shape: (3053,)

##### **Random forest**

Begin with using `GridSearchCV` to tune a random forest model.

1. Instantiate the random forest classifier `rf` and set the random state.

2. Create a dictionary `cv_params` of any of the following hyperparameters and their corresponding values to tune. The more you tune, the better your model will fit the data, but the longer it will take. 
 - `max_depth`  
 - `max_features`  
 - `max_samples` 
 - `min_samples_leaf`  
 - `min_samples_split`
 - `n_estimators`  

3. Define a set `scoring` of scoring metrics for GridSearch to capture (precision, recall, F1 score, and accuracy).

4. Instantiate the `GridSearchCV` object `rf1`. Pass to it as arguments:
 - estimator=`rf`
 - param_grid=`cv_params`
 - scoring=`scoring`
 - cv: define the number of you cross-validation folds you want (`cv=_`)
 - refit: indicate which evaluation metric you want to use to select the model (`refit=_`)


**Note:** `refit` should be set to `'f1'`.<font/>
</details>

In [ ]:
# 1. Instantiate the random forest classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier(random_state=0)

# 2. Create a dictionary of hyperparameters to tune 
cv_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_samples': [None, 0.8]
}

# 3. Define a set of scoring metrics to capture
scoring = {
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'accuracy': 'accuracy'
}

# 4. Instantiate the GridSearchCV object
rf1 = GridSearchCV(
    estimator=rf,
    param_grid=cv_params,
    scoring=scoring,
    cv=5,          # 5-fold cross-validation
    refit='f1',    # select the best model based on F1 score
    n_jobs=-1      # use all cores for faster computation
)

# Fit the model on training data
rf1.fit(X_train, y_train)

# Quick check of best parameters and score
print("Best parameters:", rf1.best_params_)
print("Best F1 score:", rf1.best_score_)

Now fit the model to the training data. Note that, depending on how many options you include in your search grid and the number of cross-validation folds you select, this could take a very long time&mdash;even hours. If you use 4-fold validation and include only one possible value for each hyperparameter and grow 300 trees to full depth, it should take about 5 minutes. If you add another value for GridSearch to check for, say, `min_samples_split` (so all hyperparameters now have 1 value except for `min_samples_split`, which has 2 possibilities), it would double the time to ~10 minutes. Each additional parameter would approximately double the time.

In [ ]:
# Fit the model to the training data
rf1.fit(X_train, y_train)

# Quick check of best parameters and score
print("Best parameters:", rf1.best_params_)
print("Best F1 score from CV:", rf1.best_score_)

<details>
  <summary><h5>HINT</h5></summary>

If you get a warning that a metric is 0 due to no predicted samples, think about how many features you're sampling with `max_features`. How many features are in the dataset? How many are likely predictive enough to give good predictions within the number of splits you've allowed (determined by the `max_depth` hyperparameter)? Consider increasing `max_features`.

</details>

If you want, use `pickle` to save your models and read them back in. This can be particularly helpful when performing a search over many possible hyperparameter values.

In [ ]:
import pickle 

# Define a path to the folder where you want to save the model
path = '/home/jovyan/work/'

# Save the fitted GridSearchCV model
with open(path + 'rf_model.pkl', 'wb') as f:
    pickle.dump(rf1, f)

# Later, load the model back in
with open(path + 'rf_model.pkl', 'rb') as f:
    rf_loaded = pickle.load(f)

# Quick check: confirm loaded model works
print("Best parameters (loaded):", rf_loaded.best_params_)
print("Best F1 score (loaded):", rf_loaded.best_score_)

In [ ]:
def read_pickle(path, save_name:str):
    """
    save_name is a string.
    """
    with open(path + save_name + '.pickle', 'rb') as to_read:
        model_object = pickle.load(to_read)
    return model_object

# Example usage:
# Save
write_pickle(path, rf1, 'rf_model')

# Load
rf_loaded = read_pickle(path, 'rf_model')

# Quick check
print("Best parameters (loaded):", rf_loaded.best_params_)
print("Best F1 score (loaded):", rf_loaded.best_score_)

In [ ]:
def read_pickle(path, saved_model_name: str):
    '''
    saved_model_name is a string.
    '''
    with open(path + saved_model_name + '.pickle', 'rb') as to_read:
        model = pickle.load(to_read)
    return model

Examine the best average score across all the validation folds.

In [ ]:
# Examine best score
print("Best average F1 score across CV folds:", rf1.best_score_)

Examine the best combination of hyperparameters.

In [ ]:
# Examine best combination of hyperparameters
print("Best hyperparameters:", rf1.best_params_)

Use the `make_results()` function to output all of the scores of your model. Note that it accepts three arguments.

<details>
  <summary><h5>HINT</h5></summary>

To learn more about how this function accesses the cross-validation results, refer to the [`GridSearchCV` scikit-learn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html?highlight=gridsearchcv#sklearn.model_selection.GridSearchCV) for the `cv_results_` attribute.

</details>

In [ ]:
# Use make_results() to output scores
results_table = make_results("Random Forest", rf1, metric="f1")

print(results_table)

Call `make_results()` on the GridSearch object.

In [ ]:
# Call make_results() on the GridSearch object
results_table = make_results("Random Forest", rf1, metric="f1")

print(results_table)

Your results should produce an acceptable model across the board. Typically scores of 0.65 or better are considered acceptable, but this is always dependent on your use case. Optional: try to improve the scores. It's worth trying, especially to practice searching over different hyperparameters.

<details>
  <summary><h5>HINT</h5></summary>

For example, if the available values for `min_samples_split` were [2, 3, 4] and GridSearch identified the best value as 4, consider trying [4, 5, 6] this time.
</details>

Use your model to predict on the test data. Assign the results to a variable called `rf_preds`.

<details>
  <summary><h5>HINT</h5></summary>
    
You cannot call `predict()` on the GridSearchCV object directly. You must call it on the `best_estimator_`.
</details>

For this project, you will use several models to predict on the test data. Remember that this decision comes with a trade-off. What is the benefit of this? What is the drawback?

The benefit of using several models to predict on the test data is that you can compare performance across different algorithms and see which one generalizes best. This gives you flexibility and confidence that you’re not relying on a single approach that might have hidden weaknesses.

The drawback is that it increases complexity and computation time — training and tuning multiple models can be resource‑intensive, and interpreting results across them requires more effort.

👉 In practice, this trade‑off is worthwhile for projects like yours: you get a broader view of model performance, but you need to manage the extra time and complexity. 

# Predict on the test data
rf_preds = rf1.predict(X_test)

# Quick check of predictions
print(rf_preds[:10])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Get predictions on test data
rf_preds = rf1.predict(X_test)

# Get scores on test data
print("Accuracy:", accuracy_score(y_test, rf_preds))
print("Precision:", precision_score(y_test, rf_preds))
print("Recall:", recall_score(y_test, rf_preds))
print("F1 Score:", f1_score(y_test, rf_preds))

# Optional: detailed classification report
print("\nClassification Report:\n", classification_report(y_test, rf_preds))

# Optional: confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, rf_preds))

Use the below `get_test_scores()` function you will use to output the scores of the model on the test data.

In [ ]:
# Predict on the test data
rf_preds = rf1.predict(X_test)

# Get scores on test data
test_results = get_test_scores("Random Forest", rf_preds, y_test)

print(test_results)

1. Use the `get_test_scores()` function to generate the scores on the test data. Assign the results to `rf_test_scores`.
2. Call `rf_test_scores` to output the results.

###### RF test results

In [ ]:
# Get scores on test data
rf_preds = rf1.predict(X_test)
rf_test_scores = get_test_scores("Random Forest", rf_preds, y_test)

# Output the results
print("RF test results")
print(rf_test_scores)

**Question:** How do your test results compare to your validation results?

Your test results should be compared directly against the cross‑validation (validation) results you saw earlier.  

- If the **test scores are close to the validation scores**, that means your model generalizes well — the hyperparameters chosen during GridSearchCV are robust, and the model isn’t overfitting.  
- If the **test scores are noticeably lower**, that suggests some overfitting: the model learned patterns specific to the training folds but didn’t capture generalizable behavior.  
- If the **test scores are higher**, it can mean the validation folds were slightly harder or less representative, but usually this is rare.  

👉 In practice, you want your test scores (precision, recall, F1, accuracy) to be within the same range as your validation scores. Since you mentioned that scores of **0.65 or better are considered acceptable**, if both sets of results meet or exceed that threshold, you can conclude the model is performing acceptably across the board.

##### **XGBoost**

 Try to improve your scores using an XGBoost model.

1. Instantiate the XGBoost classifier `xgb` and set `objective='binary:logistic'`. Also set the random state.

2. Create a dictionary `cv_params` of the following hyperparameters and their corresponding values to tune:
 - `max_depth`
 - `min_child_weight`
 - `learning_rate`
 - `n_estimators`

3. Define a set `scoring` of scoring metrics for grid search to capture (precision, recall, F1 score, and accuracy).

4. Instantiate the `GridSearchCV` object `xgb1`. Pass to it as arguments:
 - estimator=`xgb`
 - param_grid=`cv_params`
 - scoring=`scoring`
 - cv: define the number of cross-validation folds you want (`cv=_`)
 - refit: indicate which evaluation metric you want to use to select the model (`refit='f1'`)

In [ ]:
# 1. Instantiate the XGBoost classifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

xgb = XGBClassifier(
    objective='binary:logistic',
    random_state=0,
    use_label_encoder=False,
    eval_metric='logloss'   # suppresses warning
)

# 2. Create a dictionary of hyperparameters to tune
cv_params = {
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5],
    'learning_rate': [0.01, 0.1, 0.2],
    'n_estimators': [100, 200, 300]
}

# 3. Define a set of scoring metrics to capture
scoring = {
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'accuracy': 'accuracy'
}

# 4. Instantiate the GridSearchCV object
xgb1 = GridSearchCV(
    estimator=xgb,
    param_grid=cv_params,
    scoring=scoring,
    cv=5,          # 5-fold cross-validation
    refit='f1',    # select the best model based on F1 score
    n_jobs=-1      # use all cores for faster computation
)

# Fit the model on training data
xgb1.fit(X_train, y_train)

# Quick check of best parameters and score
print("Best parameters:", xgb1.best_params_)
print("Best F1 score:", xgb1.best_score_)

Now fit the model to the `X_train` and `y_train` data.

In [ ]:
%%time
# Fit the model to the training data
xgb1.fit(X_train, y_train)

# Quick check of best parameters and score
print("Best parameters:", xgb1.best_params_)
print("Best F1 score from CV:", xgb1.best_score_)

Get the best score from this model.

In [ ]:
# Examine best score
print("Best average F1 score across CV folds:", xgb1.best_score_)

And the best parameters.

In [ ]:
# Examine best parameters
print("Best hyperparameters:", xgb1.best_params_)

##### XGB CV Results

Use the `make_results()` function to output all of the scores of your model. Note that it accepts three arguments.

In [ ]:
# Call 'make_results()' on the GridSearch object
xgb_cv_results = make_results("XGBoost", xgb1, metric="f1")

print(xgb_cv_results)

Use your model to predict on the test data. Assign the results to a variable called `xgb_preds`.

<details>
  <summary><h5>HINT</h5></summary>
    
You cannot call `predict()` on the GridSearchCV object directly. You must call it on the `best_estimator_`.
</details>

In [ ]:
# Get scores on test data
xgb_preds = xgb1.predict(X_test)

# Quick check of predictions
print(xgb_preds[:10])

###### XGB test results

1. Use the `get_test_scores()` function to generate the scores on the test data. Assign the results to `xgb_test_scores`.
2. Call `xgb_test_scores` to output the results.

In [ ]:
# Get scores on test data
xgb_test_scores = get_test_scores("XGBoost", xgb_preds, y_test)

# Output the results
print("XGB test results")
print(xgb_test_scores)

**Question:** Compare these scores to the random forest test scores. What do you notice? Which model would you choose?

When comparing the XGBoost test scores to the Random Forest test scores, here’s what stands out:

XGBoost generally achieves stronger F1 scores because it balances precision and recall more effectively, especially on imbalanced datasets.

Random Forest may show slightly higher accuracy, but often at the cost of recall — meaning it misses more positive cases.

If your XGBoost test scores are consistently higher across precision, recall, and F1, that indicates it is capturing the predictive signal better than Random Forest.

If the differences are small, Random Forest could still be considered for its simplicity and interpretability.

👉 Model choice: Since your project emphasizes F1 ≥ 0.65 as the key threshold, I would recommend XGBoost if its F1 score is higher than Random Forest’s. This is because F1 directly reflects the balance between precision and recall, which is critical for reliable predictions. Random Forest would only be preferable if the scores are nearly identical and ease of deployment is a priority.

Plot a confusion matrix of the model's predictions on the test data.

In [ ]:
# Generate array of values for confusion matrix
#==> ENTER YOUR CODE HERE

# Plot confusion matrix
#==> ENTER YOUR CODE HERE

**Question:** What type of errors are more common for your model?

When you compare the XGBoost test scores to the Random Forest test scores, here’s what typically stands out:

XGBoost often delivers stronger F1 scores because it balances precision and recall more effectively, especially on imbalanced datasets.

Random Forest may show slightly higher accuracy, but sometimes at the cost of recall (missing more positives).

If your XGBoost test scores are consistently higher across precision, recall, and F1, that indicates it’s capturing the signal better than Random Forest.

If the differences are small, Random Forest might still be preferable for its simplicity and interpretability.

👉 In practice, since your project emphasizes F1 ≥ 0.65 as acceptable, I would choose XGBoost if its F1 score is higher than Random Forest’s, because F1 directly reflects the balance between precision and recall. Random Forest would only be the better choice if it’s simpler to deploy and the scores are nearly identical.

##### Feature importance

Use the `feature_importances_` attribute of the best estimator object to inspect the features of your final model. You can then sort them and plot the most important ones.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Get feature importances from the best estimator
importances = xgb1.best_estimator_.feature_importances_

# Pair with feature names
feature_importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
})

# Sort by importance
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Display top features
print(feature_importance_df.head(10))

# Plot top features
plt.figure(figsize=(8,6))
plt.barh(feature_importance_df['Feature'][:10], feature_importance_df['Importance'][:10])
plt.gca().invert_yaxis()  # highest importance at top
plt.title("Top 10 Feature Importances (XGBoost)")
plt.xlabel("Importance Score")
plt.show()

<img src="images/Execute.png" width="100" height="100" align=left>

## PACE: **Execute**

Consider the questions in your PACE Strategy Document to reflect on the Execute stage.

### **Task 4. Conclusion**

In this step, use the results of the models above to formulate a conclusion. Consider the following questions:

1. **Would you recommend using this model? Why or why not?**  

2. **What was your model doing? Can you explain how it was making predictions?**   

3. **Are there new features that you can engineer that might improve model performance?**   

4. **What features would you want to have that would likely improve the performance of your model?**   

Remember, sometimes your data simply will not be predictive of your chosen target. This is common. Machine learning is a powerful tool, but it is not magic. If your data does not contain predictive signal, even the most complex algorithm will not be able to deliver consistent and accurate predictions. Do not be afraid to draw this conclusion. Even if you cannot use the model to make strong predictions, was the work done in vain? Consider any insights that you could report back to stakeholders.

**Congratulations!** You've completed this lab. However, you may not notice a green check mark next to this item on Coursera's platform. Please continue your progress regardless of the check mark. Just click on the "save" icon at the top of this notebook to ensure your work has been logged.